apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: auovcbuk2-nodejs 
  janus-idp.io/tekton: auovcbuk2-nodejs
  backstage.io/kubernetes-id: auovcbuk2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: auovcbuk2-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml